<a href="https://colab.research.google.com/github/madinayergeshbay-sudo/2026_Spring_Application_Programming/blob/main/mad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install beautifulsoup4 requests

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

In [ ]:
%%writefile index.html

<html>
<head><title>The Dormouse's story</title></head>
<body>

<p class="title"><b>The Dormouse's story</b></p>

<h1>Beautiful Soup</h1>

<p class="story">
Once upon a time there were three little sisters;
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a>,
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>
and they lived at the bottom of a well.
</p>

</body>
</html>

Writing index.html

In [ ]:
from bs4 import BeautifulSoup

file = open("index.html", "r")
html = file.read()

soup = BeautifulSoup(html, "html.parser")

print(soup)

<html>
<head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>
<h1>Beautiful Soup</h1>
<p class="story">
Once upon a time there were three little sisters;
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>,
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>
and they lived at the bottom of a well.
</p>
</body>
</html>

In [ ]:
print(soup.get_text())

The Dormouse's story

The Dormouse's story
Beautiful Soup

Once upon a time there were three little sisters;
Elsie,
Lacie,
Tillie
and they lived at the bottom of a well.

In [ ]:
print(soup.find("h1"))

<h1>Beautiful Soup</h1>

In [ ]:
links = soup.find_all("a")

for link in links:
    print(link)

<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>

In [ ]:
for link in links:
    print(link.text)

Elsie
Lacie
Tillie

In [ ]:
for link in links:
    print(link.get("href"))

http://example.com/elsie
http://example.com/lacie
http://example.com/tillie

In [ ]:
title = soup.find("p", class_="title")
print(title.text)

The Dormouse's story

In [ ]:
link1 = soup.find(id="link1")
print(link1.text)

Elsie

In [ ]:
print(soup.select("a"))

[<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>, <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>, <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>]

In [ ]:
import requests
from bs4 import BeautifulSoup

url = 'https://kin.naver.com/search/list.nhn?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC'

response = requests.get(url)

if response.status_code == 200:
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    print(soup)

else :
    print(response.status_code)

<!DOCTYPE html>

<html lang="ko">
<head>
<meta contents="always" name="referrer"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="파이썬의 지식iN Q&amp;A 검색결과입니다. 궁금증을 해결하지 못했다면 지식iN '질문하기'를 해보세요." name="description">
<meta content="width=1024" name="viewport"/>
<meta content="none" name="msapplication-config">
<link href="https://ssl.pstatic.net/static.kin/static/pc/20260325142329/css/min/common.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/static.kin/static/pc/20260325142329/css/min/components.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/static.kin/static/pc/20260325142329/css/min/other.css" rel="stylesheet" type="text/css"/>
<script>

	var pcDomain = "kin.naver.com";
	var pcDomainWithProtocol = "https://kin.naver.com";
	var pcKinServiceProtocol = "https";

	var mobileDomain = "m.kin.naver.com";
	var mobileDomainWithProtocol = "https://m.kin.naver.com";
	var mobileKinServiceProtocol = "https";

	var uploadDomain = "upload.kin.naver.com";
	var uploadDomainWithProtocol = "https://upload.kin.naver.com";
	var uploadKinServiceProtocol = "https";
</script>
<script src="https://ssl.pstatic.net/static.kin/static/pc/20260325142329/js/min/kin.js" type="text/javascript"></script>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="noindex,nofollow" name="robots">
<meta content="파이썬 검색결과 : 네이버 지식iN" property="og:title">
<meta content="https://kin.naver.com/search/list.nhn?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC" property="og:url"/>
<meta content="https://ssl.pstatic.net/static/kin/common/kin_thumbnail_new_w1000.png" property="og:image"/>
<meta content="파이썬의 지식iN Q&amp;A 검색결과입니다. 궁금증을 해결하지 못했다면 지식iN '질문하기'를 해보세요." property="og:description"/>
<meta content="네이버 지식iN" property="og:article:author"/>
<meta content="https://kin.naver.com" property="og:article:author:url"/>
<link href="/favicon.ico?v=2.4" rel="shortcut icon" type="image/x-icon"/>
<title>
	파이썬 검색결과 : 지식iN
</title>
<script type="text/javascript">

if ( typeof window.nhn  == "undefined" ) window.nhn = {};
if ( typeof window.naver  == "undefined" ) window.naver = {};
nhn.isLogin = false;
nhn.isJunior = ("N"=="Y");
nhn.isKinUser = false;
nhn.isPortableDevice = false;
nhn.jsDir = 'https://ssl.pstatic.net/static.kin/static/pc/20260325142329/js/min';

var g_ssc = ("kin.search" == "") ? "kin.temp" : "kin.search";
var ccsrv="cc.naver.com";


var kinRos = {
	bIsNoticeDisplay : ("false" == "" || "false" == "false") ? false : true,
	bIsActionNoticeDisplay : ("false" == "" || "false" == "false") ? false : true

};





var standardReportPopupUrl = "https://srp2.naver.com/report";


var baUserKey = "__UNKNOWN__";
var baLogEndpoint = "https://scv-kin.io.naver.com/jackpotlog/v1/logs";
var baAbTestResult = null;
</script>
</meta></meta></meta></meta></head>
<body>
<div id="loadingIndicator" style="display:none;width:100%;height:100%;position:fixed;top:0px;left:0px;background-color:transparent;z-index:10000;">
<img alt="데이터 요청 응답 대기중" height="21" src="https://ssl.pstatic.net/static/kin/m/ico_lod2.gif" style="position:absolute;top:49%;left:49%;" width="21"/>
</div>
<div class="wrap wrap_search" id="wrap">
<div class="skip_nav header_gnb_inner">
<a class="skip" href="#gnb" onclick="nhn.Kin.Utility.skipNavigation('au_lnb_home');return false;">메인 메뉴 바로가기</a>
<a class="skip" href="#s_content" onclick="nhn.Kin.Utility.skipNavigation('s_content');return false;">본문 바로가기</a>
</div>
<div class="header_wrap">
<div aria-labelledby="ieUpdateBannerTitle" class="popup popup--header_notice" id="ieUpdateBanner" role="dialog" style="display: none;">
<h1 class="blind" id="ieUpdateBannerTitle" tabindex="0">권장 브라우저 업데이트 안내</h1>
<div class="popup__content">
<div class="popup__title">
<p class="popup__title_text"><span class="ico_alert sp_common"></span>권장 브라우저 안내</p>
</div>
<div class="popup__maintext">
<p class="popup__text">혹시 아직 인터넷 익스플로러 9.0 미만 버전을 사용하고 계신가요?</p>
<p class="popup__subtext">새롭게 바뀐 지식iN Q&amp;A 페이지는 IE 9.0 이상의 브라우저에 최적화되어 있습니다. 원활한 이용을 위해 꼭 업데이트 해주세요! <a class="popup__link" href="https://support.microsoft.com/ko-kr/help/17621/internet-explorer-downloads" target="_blank">업데이트하기 <span class="sp_common ico_arr_lnk"></span></a></p>
</div>
</div>
</div>
<script type="text/javascript">
	// IE8 이하이면 브라우저 버전을 올려달라는 배너를 노출한다.
	$Fn(function() {
		var oAgent = jindo.$Agent().navigator();
		if (oAgent.ie && (oAgent.version >= 6 && oAgent.version < 9)) {
			if (typeof naver.kin.SimpleBanner !== "undefined") {
				var oIeUpdateBanner = new naver.kin.SimpleBanner({
					sBannerId: "ieUpdateBannerArea"
				});
			}
		}
	}, this).attach(document, 'domready');
</script>
<div class="header_gnb">
<div class="header_gnb_inner">
<h1 class="header_logo">
<a class="logo_naver" href="http://www.naver.com" onclick="nhn.Kin.Utility.nClicks('STA.naverlogo', '', '', event);" title="나의 경쟁력, 네이버"><span class="blind">NAVER</span></a>
</h1>
<h2 class="logo_wrap">
<a class="icon_logo_kin" href="/" onclick="nhn.Kin.Utility.nClicks('STA.kin', '', '', event);"><span class="blind">지식iN</span></a>
</h2>
<div class="header_search">
<h3 class="blind">검색영역</h3>
<form action="/search/list.naver" id="topSearch" method="get" name="topSearch" onsubmit="return checkQuery();">
<fieldset>
<legend>지식인 검색</legend>
<div class="search_area">
<input accesskey="s" aria-autocomplete="list" aria-controls="atcmpList" aria-expanded="false" aria-haspopup="listbox" autocomplete="off" class="search_input" id="nx_query" maxlength="255" name="query" onclick="nhn.Kin.Utility.nClicks('STA.search', '', '', event);return false;" role="combobox" title="검색어 입력" type="text" value="파이썬"/>
<a class="search_auto" href="#">
<span class="sp_gnb icon_arrow" id="triangleBtn">자동완성 열기</span>
</a>
<div>
<iframe class="auto_complete_box" frameborder="0" height="193px" id="autoFrame" marginheight="0" marginwidth="0" scrolling="no" title="검색어 자동완성" width="290"></iframe>
</div>
<a class="search_btn" href="#" onclick="return checkQuery();"><span class="sp_gnb icon_search">지식iN 검색</span></a>
</div>
</fieldset>
</form>
</div>
<div class="header_tool">
<div class="header__rolling rolling-notice">
<i class="icon_speaker"><span class="blind">실시간 공지사항</span></i>
<ul class="rolling-notice__list _rolling_banner" id="listNotice">
<li class="rolling-notice__item _rollingItem" data-start-time="2023-07-03 00:00:00" style="display:none;">
<a class="rolling-notice__link" href="https://m.expert.naver.com/mobile/expert/account/join/hub" onclick="nhn.Kin.Utility.nClicks('STA.event', '', '', event);">
<i class="icon_new_red _newMark" style="display:none;"><span class="blind">새소식</span></i>
<span class="text-color--secondary">지식iN은 누구나 엑스퍼트</span><br/>
</a>
</li>
</ul>
</div>
<div class="gnb_eXpertLogo">
<a aria-controls="bannerExpert" aria-expanded="true" aria-haspopup="true" class="link" href="https://expert.naver.com" id="bannerLink" rel="noopener noreferrer" target="_blank">
<span class="logo"><span class="blind">eXpert</span></span>
<span class="blind">새 창</span>
</a>
</div>
<div class="gnb_wrap">
<div class="gnb_common_area">
<div id="gnb">
<script type="text/javascript">

							var gnb_service = "kin";

							var gnb_logout = encodeURIComponent("https://nid.naver.com/nidlogin.logout");

							var gnb_login = encodeURIComponent(location.href || 'https://kin.naver.com');

							var gnb_template = "gnb_utf8";

							var gnb_item_hide_option = 0;




						</script>
<script charset="utf-8" src="https://ssl.pstatic.net/static.gn/templates/gnb_utf8.nhn?2026040312" type="text/javascript"></script>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- nav -->
<div class="nav" role="navigation">
<div class="nav_inner">
<h3 class="blind">메인 메뉴</h3>
<ul class="nav_list" id="au_lnb" role="menubar">
<li class="menu" role="presentation">
<a class="item" href="/index.naver" id="au_lnb_home" onclick="nhn.Kin.Utility.nClicks('LNB.home', '', '', event);" role="menuitem" tabindex="0"><em>홈</em></a>
</li>
<li class="menu" role="presentation">
<a aria-expanded="false" aria-haspopup="true" class="item" href="/qna/list.naver" onclick="nhn.Kin.Utility.nClicks('LNB.qna', '', '', event);" role="menuitem" tabindex="-1"><em>Q&amp;A</em></a>
<ul class="nav_sub_list _lnbSubMenu" role="menu">
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=11" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '11', '1', event);" role="menuitem" tabindex="-1">교육, 학문</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=1" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '1', '2', event);" role="menuitem" tabindex="-1">IT/테크</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=2" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '2', '3', event);" role="menuitem" tabindex="-1">게임</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=3" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '3', '4', event);" role="menuitem" tabindex="-1">엔터테인먼트, 예술</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=8" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '8', '5', event);" role="menuitem" tabindex="-1">생활</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=7" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '7', '6', event);" role="menuitem" tabindex="-1">건강</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=6" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '6', '7', event);" role="menuitem" tabindex="-1">사회, 정치</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=4" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '4', '8', event);" role="menuitem" tabindex="-1">경제</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=9" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '9', '9', event);" role="menuitem" tabindex="-1">여행</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=10" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '10', '10', event);" role="menuitem" tabindex="-1">스포츠, 레저</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=5" onclick="nhn.Kin.Utility.nClicks('LNB.kinlayer', '5', '11', event);" role="menuitem" tabindex="-1">쇼핑</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=13" onclick="nhn.Kin.Utility.nClicks('LNB.jun', '', '', event);" role="menuitem" tabindex="-1">쥬니버Q&amp;A</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=12" onclick="nhn.Kin.Utility.nClicks('LNB.loc', '', '', event);" role="menuitem" tabindex="-1">지역&amp;플레이스</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/qna/list.naver?dirId=20" onclick="nhn.Kin.Utility.nClicks('LNB.talk', '', '', event);" role="menuitem" tabindex="-1">고민Q&amp;A</a></li>
<li class="sub_menu" role="presentation"><a class="item" href="/opendic/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.open', '', '', event);" role="menuitem" tabindex="-1">오픈사전</a></li>
</ul>
</li>
<li class="menu" role="presentation">
<a class="item" href="/qna/questionList.naver" onclick="nhn.Kin.Utility.nClicks('LNB.answer', '', '', event);" role="menuitem" tabindex="-1"><em>답변하기</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/volunteer/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.donation', '', '', event);" role="menuitem" tabindex="-1"><em>지식기부</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/people/elite/index.naver?from=lnb" id="peopleLnbBtn" onclick="nhn.Kin.Utility.nClicks('LNB.people', '', '', event);" role="menuitem" tabindex="-1"><em>사람들</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/best/listaha.naver" onclick="nhn.Kin.Utility.nClicks('LNB.best', '', '', event);" role="menuitem" tabindex="-1"><em>베스트</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/hall/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.honor', '', '', event);" role="menuitem" tabindex="-1"><em>명예의전당</em></a>
</li>
<li class="menu" role="presentation">
<span class="lnb_bar">|</span>
<a class="item" href="/myinfo/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.profile', '', '', event);" role="menuitem" tabindex="-1"><em>프로필</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/partnercenter/index.naver" onclick="nhn.Kin.Utility.nClicks('LNB.partner', '', '', event);" role="menuitem" tabindex="-1"><em>파트너센터</em></a>
</li>
<li class="menu" role="presentation">
<a class="item" href="/roulette/home.naver" onclick="nhn.Kin.Utility.nClicks('LNB.roulette', '', '', event);" role="menuitem" tabindex="-1"><em>룰렛</em></a>
</li>
</ul>
<a class="nav__button_question _clickcode:LNB.q" href="#" onclick="nhn.Kin.checkRosAndGoUrl(event, '/qna/question.naver', '');sendBaLog(BaPcEventType.KIN_HOME_5048)" role="button"><span class="btn_inner"><i class="sp_gnb icon_pencil"></i>질문하기</span></a>
</div>
</div>
</div>
<script type="text/javascript">

	$Fn(function() {
		new naver.kin.LNB({
			'questionType' : ''
		});
	}).attach(window, 'load');

	var GNB_BRIGHTNESS_VALUE = {
		DARK_ICON : 0,
		DARK_ICON_AND_TRANSPARENCY : 1,
		BRIGHT_ICON_AND_TRANSPARENCY : 2,
		BRIGHT_ICON : 3
	};

	var GNB_ITEM_HIDE_OPTION_BIT_VALUE = {
		DEFAULT : 0,
		HIDE_LOGIN_BTN : 1,
		HIDE_USER_LAYER : 2,
		HIDE_NAVER_ME_AREA : 4,
		HIDE_MAIL_ALARM_AREA : 8,
		HIDE_PROFILE_IMAGE : 16,
		SHOW_BENEFIT_FOR_STAFF_MEMBER : 32
	};


	var smartSearch = "";

	var gnb_service = "kin";

	var gnb_logout = encodeURIComponent("https://nid.naver.com/nidlogin.logout");

	var gnb_login = encodeURIComponent(location.href || 'https://kin.naver.com');

	var gnb_template = "gnb_utf8";

	var gnb_item_hide_option = GNB_ITEM_HIDE_OPTION_BIT_VALUE.DEFAULT;





	$Fn(function() {

		getGNB();

		var bIsGnbClicked = false;


		$Fn(function (we) {
			if (!bIsGnbClicked) {
				gnbAllLayerClose();
			}

			bIsGnbClicked = false;
		}, this).attach(document.body, 'click');

		$Fn(function(we) {
			bIsGnbClicked = true;
		}, this).attach($('gnb'), 'click');


		try {
			$('autoFrame').src = '/static/reatcmp.html?v=4.1';
		} catch(e) {
		}

		smartSearch = new nhn.AjaxSuggestUS('nx_query', 'autoFrame', {
			url : 'https://ac.search.naver.com/nx/ac',
			cookieName : 'NaverSuggestUse',
			listbox : '_resultBox',
			sFromName : 'topSearch',
			triangleBtn : 'triangleBtn',
			sListMaxLength : 55,
			listMaxCount : 15,
			request_type : 'jsonp',
			request_data : {
				q : '{query}',
				st : '100',
				r_format : 'json',
				t_koreng : '1',
				q_enc : 'UTF-8',
				r_enc : 'UTF-8',
				r_unicode : '0',
				r_escape : '1',
				frm : 'kin'
			},
			sTriangleUpOn : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_up.gif',
			sTriangleUpOff : 'https://ssl.pstatic.net/sstatic/search/mypocket/v3/btn_atcmp_off_op2.gif',
			sTriangleDownOn : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_down.gif',
			sTriangleDownOff : 'https://ssl.pstatic.net/static/common/snb/090513/bu_arrow_down3.gif'
		}).attach({
			actSubmit : function() {
				try {
					top.selectAction(this._elForm);
				} catch(e) {
					try {
						selectAction(this._elForm);
					} catch(e) {
					}
				}

				this._elForm.submit();
			}
		});

		var expertEntryBanner = $$.getSingle("div.gnb_eXpertLogo div.banner");
		if (!!expertEntryBanner) {
			var cookie = new $Cookie();

			$Fn(function () {
				$Element(expertEntryBanner).hide();

				var newDisabledUntil = new Date().getTime() + (3 * 1000 * 24 * 60 * 60);
				cookie.set("kin_expert_entry_banner_disabled_until", newDisabledUntil, 5);
			}).attach($$.getSingle("div.gnb_eXpertLogo div.banner button.buttonCancel"), 'click');

			var disabledUntilTimestamp = new Number(cookie.get("kin_expert_entry_banner_disabled_until"));
			if (!isNaN(disabledUntilTimestamp)) {
				if (new Date().getTime() > disabledUntilTimestamp) {
					cookie.remove("kin_expert_entry_banner_disabled_until");
					$Element(expertEntryBanner).show();
				}
			} else {
				$Element(expertEntryBanner).show();
			}
		}


		if (typeof nhn.Kin.ChatMenu !== "undefined") {
			window.oChatMenu = new nhn.Kin.ChatMenu();
		}
	}).attach(window, 'load');
</script>
<div class="container-fluid" id="container">
<div class="container-fluid-content">
<div class="container-fluid-content-inner">
<div id="search_result">
<strong>'파이썬'</strong> 에 대한 검색결과입니다.



</div>
<script type="text/javascript">
function checkAdultAuth() {
	var url = "https://" + top.location.hostname + "/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&cs=utf8&section=kin&excludeAdultDoc=false";
	var surl = "https://" + top.location.hostname + "/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&cs=utf8&section=kin";

	try{


			top.location.href = "https://nid.naver.com/nidlogin.login?svctype=128&a_version=2&viewtype=2&url=" + encodeURIComponent(url + "&from=search") + "&surl=" + encodeURIComponent(surl);

	} catch (e){
		history.back();
	}
}
</script>
<div class="container-fluid-content__left" id="content">
<script src="https://ssl.pstatic.net/static.kin/static/pc/20260325142329/js/min/nhn.Kin.Search.Terms.js" type="text/javascript"></script>
<div id="s_content">
<div id="scl">
<ul>
<li class="tx_depth1"><strong><a class="_nclicks:tab.kin" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=kin" title="전체"><span>전체</span></a></strong></li>
<li class="tx_depth2"><a class="_nclicks:tab.qna" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna" title="Q&amp;A"><span>Q&amp;A</span></a></li>
<li class="tx_depth3"><a class="_nclicks:tab.ency" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=ency" title="오픈백과"><span>오픈백과</span></a></li>
<li>
</li></ul>
</div>
<div class="banner_suicide_stop" id="suicidalPreventionBanner" style="display:none;">
<div class="content_suicide_stop">
<h3 class="tit_suicide_stop">
<span class="blind">생명은 소중합니다.! 지금,희망을 클릭하세요.</span>
</h3>
<ul class="info_suicide_stop">
<li class="counsel_list v1">
<strong class="tit_counsel_list">전화상담</strong>
<ul class="counsel_info_list">
<li>자살예방상담전화 <em>109</em></li>
<li>정신건강상담전화 <em>1577-0199</em></li>
<li><a href="https://www.cyber1388.kr:447" target="_blank">청소년 HelpCall</a> <em>1388</em></li>
<li><a href="https://www.lifeline.or.kr" target="_blank">한국생명의전화</a> <em>1588-9191</em></li>
<li>한마음한몸자살예방센터 <em>1577-0199</em></li>
</ul>
</li>
<li class="counsel_list v2">
<strong class="tit_counsel_list">온라인상담</strong>
<ul class="counsel_info_list">
<li><a href="https://www.lifeline.or.kr" id="btn_suicide_stop" target="_blank">한국생명의전화</a></li>
<li><a href="https://www.cyber1388.kr:447" target="_blank">청소년사이버상담센터</a></li>
</ul>
</li>
<li class="counsel_list v3">
<strong class="tit_counsel_list">지식iN도 여러분을 돕습니다.</strong>
<ul class="counsel_info_list">
<li><a href="/qna/question.naver?expertType=doctor&amp;dirId=70109" target="_blank">의사에게질문하기</a></li>
<li><a href="/profile/index.naver?u=6oCfeacJKVQGwsBB7OHEIS4miiPixwQ%2FoueervNeYrg%3D" target="_blank">여성가족부. 한국청소년상담복지개발원</a></li>
<li><a href="/profile/index.naver?u=9xhBJX%2Fe3worDHM4Tp9d%2F4jUxoIMOWjkBn9VK4u3x8M%3D" target="_blank">경기도청소년상담복지센터</a></li>
<li class="list_aside"><a href="/profile/index.naver?u=m61fd7AyyTNGzdSXnfIARZMD2YrqU0TvSai8n3aIfHk%3D" target="_blank">마음상담</a></li>
<li><span class="counsel_vt">|</span><a href="/profile/index.naver?u=9AFcqSNT5xcmX%2BDwjqumdFA11U6ypJgxKXiNTqx%2FenU%3D" target="_blank">허그맘</a></li>
</ul>
</li>
</ul>
</div>
</div>
<script type="text/javascript">
	jindo.$Fn(function() {


		if(nhn.Kin.Utility.containSuicideKeywords('\uD30C\uC774\uC36C')) {

			jindo.$Element('suicidalPreventionBanner').show();
		}
	},this).attach(window,"load");
	</script>
<div class="section">
<h2>

In [ ]:
import requests
from bs4 import BeautifulSoup

url = 'https://kin.naver.com/search/list.nhn?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC'

response = requests.get(url)

if response.status_code == 200:
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    title = soup.select_one('#s_content > div.section > ul > li:nth-child(1) > dl > dt > a')
    print(title)
else :
    print(response.status_code)

<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=1&amp;dirId=10402&amp;docId=490918994&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b> 전망이 어떻게 되나요</a>

In [ ]:
print(title.get_text())

파이썬 전망이 어떻게 되나요

In [ ]:
import requests
from bs4 import BeautifulSoup

url = 'https://kin.naver.com/search/list.nhn?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC'

response = requests.get(url)

if response.status_code == 200:
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    ul = soup.select_one('ul.basic1')
    print(ul)
else :
    print(response.status_code)

<ul class="basic1">
<li>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=1&amp;dirId=10402&amp;docId=490918994&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b> 전망이 어떻게 되나요</a>
</dt>
<dd class="txt_inline">2025.12.22.</dd>
<dd><b>파이썬</b>을 제대로 공부해서 돈 벌고 싶은데... 보통 <b>파이썬</b> 공부하시는 분들은 돈을 어떻게 버나요? 프리랜서로 일해서 버나요? <b>파이썬</b>"만" 배우신다면 딱히 전망이 있진... </dd>
<dd class="tag_area">
<a class="em _nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%8C%8C%EC%9D%B4%EC%8D%AC&amp;listType=answer">#파이썬</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%BD%94%EB%94%A9&amp;listType=answer">#파이썬코딩</a>
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=10402">웹프로그래밍</a>
<span class="bar">|</span>
<span class="hit">답변수 4</span> UP 1


							</dd>
</dl>
</li>
<li>
<div class="thumb">
<a class="_nclicks:kin.img" href="https://kin.naver.com/qna/detail.naver?d1id=1&amp;dirId=10402&amp;docId=490656160&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><img alt="파이썬코드좀" onerror="this.parentNode.parentNode.style.display='none';" src="https://kin-phinf.pstatic.net/20251209_45/1765234443035VvWC7_PNG/image01.png?type=m100"/></a>
</div>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=1&amp;dirId=10402&amp;docId=490656160&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b>코드좀</a>
</dt>
<dd class="txt_inline">2025.12.09.</dd>
<dd><b>파이썬</b>초보인데 <b>파이썬</b>코드좀알려주세요 설치하기 https://www.python.... html 크롬에서 번역기 이용, 또는구글 번역기 이용 <b>파이썬</b> 특징... </dd>
<dd class="tag_area">
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=10402">웹프로그래밍</a>
<span class="bar">|</span>
<span class="hit">답변수 4</span> UP 0


								<span class="bar">|</span>


									답변





										<img alt="TOP 50" class="ico_top5" height="11" src="https://ssl.pstatic.net/static/kin/09renewal/ico_badge_top50.gif" width="30">






									오렌지팜(i_****)



							</img></dd>
</dl>
</li>
<li>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=10&amp;dirId=100507&amp;docId=492544601&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank">아두이노 R3보드 <b>파이썬</b> 사용</a>
</dt>
<dd class="txt_inline">2026.03.19.</dd>
<dd>취미로 아두이노 해 보려 하는데 <b>파이썬</b>으로 코딩이 될까요? Q는 가능한 것 같은데... 아주 옛날에 pymite라고 해서 그런 칩에서도 <b>파이썬</b>을 올리는 시도가 있긴 했으나... </dd>
<dd class="tag_area">
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%EC%95%84%EB%91%90%EC%9D%B4%EB%85%B8&amp;listType=answer">#아두이노</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%EC%95%84%EB%91%90%EC%9D%B4%EB%85%B8r3&amp;listType=answer">#아두이노r3</a>
<a class="em _nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%8C%8C%EC%9D%B4%EC%8D%AC&amp;listType=answer">#파이썬</a>
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=100507">모터스포츠경주</a>
<span class="bar">|</span>
<span class="hit">답변수 3</span> UP 0


							</dd>
</dl>
</li>
<li>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=1&amp;dirId=11001&amp;docId=492614778&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b> 해킹과보안</a>
</dt>
<dd class="txt_inline">2026.03.24.</dd>
<dd><b>파이썬</b> 해킹 레시피란책이 기본문법20%정도되고 나머지80%는 다 해킹코드들이적힌책인가요? <b>파이썬</b>으로 해킹과 보안에 대해 배우고 싶으시군요! "<b>파이썬</b> 해킹 레시피... </dd>
<dd class="tag_area">
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=AI%EB%8B%B5%EB%B3%80&amp;listType=answer">#AI답변</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%8C%8C%EC%9D%B4%EC%8D%AC%ED%95%B4%ED%82%B9&amp;listType=answer">#파이썬해킹</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%EB%B3%B4%EC%95%88%EC%B1%85%EC%B6%94%EC%B2%9C&amp;listType=answer">#보안책추천</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%95%B4%ED%82%B9%EB%A0%88%EC%8B%9C%ED%94%BC&amp;listType=answer">#해킹레시피</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%BD%94%EB%93%9C%EB%B6%81&amp;listType=answer">#파이썬코드북</a>
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=11001">해킹</a>
<span class="bar">|</span>
<span class="hit">답변수 3</span> UP 0


								<span class="bar">|</span>


									답변





										<img alt="TOP 50" class="ico_top5" height="11" src="https://ssl.pstatic.net/static/kin/09renewal/ico_badge_top50.gif" width="30">






									지식이(nv_k****)



							</img></dd>
</dl>
</li>
<li>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=1&amp;dirId=11001&amp;docId=492625548&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b> 해킹 레시피</a>
<img alt="지식파트너 답변" class="ico_pro" height="14" src="https://ssl.pstatic.net/static/kin/09renewal/ico_kin_partner.gif" width="51"/>
</dt>
<dd class="txt_inline">2026.03.24.</dd>
<dd><b>파이썬</b> 해킹 레시피란 책을 사려고하는데 이책에는... 암호화 및 복호화: <b>파이썬</b>을 이용한 간단한 암호 알고리즘 구현. * 실습 환경 구축: 작성하신... </dd>
<dd class="tag_area">
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=11001">해킹</a>
<span class="bar">|</span>
<span class="hit">답변수 4</span> UP 1


								<span class="bar">|</span>


									답변






										<img alt="TOP 20" class="ico_top5" height="11" src="https://ssl.pstatic.net/static/kin/09renewal/ico_badge_top20.gif" width="30">






									it****


							</img></dd>
</dl>
</li>
<li>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=4&amp;dirId=40608&amp;docId=490121419&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b> 잘하면 엔지니어로 일할 수 있나요?</a>
</dt>
<dd class="txt_inline">2025.11.12.</dd>
<dd><b>파이썬</b> -&gt; c언어 -&gt; 자바 ?? 순인가요? 안녕하세요! IT의... <b>파이썬</b>으로도 충분히 엔지니어가 될 수 있을까?... 1) <b>파이썬</b>으로 가능한 엔지니어 분야 * 데이터 분석 / 인공지능... </dd>
<dd class="tag_area">
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=40608">컴퓨터, 프로그래밍</a>
<span class="bar">|</span>
<span class="hit">답변수 6</span> UP 2


							</dd>
</dl>
</li>
<li>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=10&amp;dirId=100507&amp;docId=490509786&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b> 코드로 드론 날리기</a>
</dt>
<dd class="txt_inline">2025.12.01.</dd>
<dd>제가 <b>파이썬</b>을 이용하여 드론을 날리는걸 연습하고 있어요 그래서 드론을 날렸을때... 드론은 그냥 작은 드론 입니다 <b>파이썬</b> 코드 알려주시면 감사하겠습니다 ! <b>파이썬</b>으로... </dd>
<dd class="tag_area">
<a class="em _nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%8C%8C%EC%9D%B4%EC%8D%AC&amp;listType=answer">#파이썬</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%EC%BD%94%EB%94%A9&amp;listType=answer">#코딩</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%EB%93%9C%EB%A1%A0&amp;listType=answer">#드론</a>
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=100507">모터스포츠경주</a>
<span class="bar">|</span>
<span class="hit">답변수 1</span> UP 0


							</dd>
</dl>
</li>
<li>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=5&amp;dirId=50202&amp;docId=492319206&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b>에 필요한 노트북 사양</a>
</dt>
<dd class="txt_inline">2026.03.05.</dd>
<dd>... <b>파이썬</b> 쓴다는데 레노버 아이디어 패드 슬림3 15iru8로 돌아갈까요? 간단한 작업 밖에 안하는 거 같아요. <b>파이썬</b>... 프로그래밍, <b>파이썬</b> 초급 또는 중급 수준의 작업에는... </dd>
<dd class="tag_area">
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=50202">노트북</a>
<span class="bar">|</span>
<span class="hit">답변수 5</span> UP 2


								<span class="bar">|</span>


									답변



									기가요 인터넷가입(germ****)



							</dd>
</dl>
</li>
<li>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=1&amp;dirId=10402&amp;docId=492607487&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b> 해킹과보안</a>
</dt>
<dd class="txt_inline">2026.03.23.</dd>
<dd>제가 <b>파이썬</b> 해킹과보안에관심이있어서 해커의 언어 <b>파이썬</b> 3 입문책을샀는데 그책은 95%가 문법만나와서... 해킹코드들이있는책을사고싶은데 <b>파이썬</b> 해킹 레시피라는책은... </dd>
<dd class="tag_area">
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=10402">웹프로그래밍</a>
<span class="bar">|</span>
<span class="hit">답변수 1</span> UP 0


								<span class="bar">|</span>


									답변



									올이(sat0****)



							</dd>
</dl>
</li>
<li>
<dl>
<dt>
<a class="_nclicks:kin.txt _searchListTitleAnchor" href="https://kin.naver.com/qna/detail.naver?d1id=1&amp;dirId=10402&amp;docId=360647365&amp;qb=7YyM7J207I2s&amp;enc=utf8" target="_blank"><b>파이썬</b> 등을 통한 업무 자동화로 쇼핑몰... </a>
</dt>
<dd class="txt_inline">2026.03.30.</dd>
<dd>... 이번에 우연히 <b>파이썬</b>을 통한 업무자동화 등을 접하게... 것같아, <b>파이썬</b>을 통한 업무 자동화에 도전해보려고 합니다. 1. <b>파이썬</b> 등 프로그램을 통한 업무 자동화를... </dd>
<dd class="tag_area">
<a class="em _nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%8C%8C%EC%9D%B4%EC%8D%AC&amp;listType=answer">#파이썬</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%BD%94%EB%94%A9&amp;listType=answer">#파이썬코딩</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%ED%8C%8C%EC%9D%B4%EC%8D%AC%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D&amp;listType=answer">#파이썬프로그래밍</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%EC%97%85%EB%AC%B4%EC%9E%90%EB%8F%99%ED%99%94&amp;listType=answer">#업무자동화</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%EC%97%85%EB%AC%B4%EC%9E%90%EB%8F%99%ED%99%94%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8&amp;listType=answer">#업무자동화프로그램</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%EC%BD%94%EB%94%A9&amp;listType=answer">#코딩</a>
<a class="_nclicks:kin.tag" href="/tag/tagDetail.naver?tag=%EC%BD%94%EB%94%A9%EA%B3%B5%EB%B6%80&amp;listType=answer">#코딩공부</a>
</dd>
<dd class="txt_block">
<a class="txt_g1 _nclicks:kin.cat1" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna">Q&amp;A</a>

									 &gt; <a class="txt_g1 _nclicks:kin.cat2" href="/search/list.naver?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC§ion=qna&amp;dirId=10402">웹프로그래밍</a>
<span class="bar">|</span>
<span class="hit">답변수 2</span> UP 0


							</dd>
</dl>
</li>
</ul>

Web Crawling and Scrapping 실습

기본 연습 — 책 제목 20개 가져오기

In [27]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "http://books.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

titles = [a["title"] for a in soup.select("h3 a")]

for title in titles:
    print(title)

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

제목을 표로 만들기

In [28]:
df_titles = pd.DataFrame(titles, columns=["Book Title"])
df_titles

                                           Book Title
0                                A Light in the Attic
1                                  Tipping the Velvet
2                                          Soumission
3                                       Sharp Objects
4               Sapiens: A Brief History of Humankind
5                                     The Requiem Red
6   The Dirty Little Secrets of Getting Your Dream...
7   The Coming Woman: A Novel Based on the Life of...
8   The Boys in the Boat: Nine Americans and Their...
9                                     The Black Maria
10     Starving Hearts (Triangular Trade Trilogy, #1)
11                              Shakespeare's Sonnets
12                                        Set Me Free
13  Scott Pilgrim's Precious Little Life (Scott Pi...
14                          Rip it Up and Start Again
15  Our Band Could Be Your Life: Scenes from the A...
16                                               Olio
17  Mesaerion: The Best Science Fiction Stories 18...
18                       Libertarianism for Beginners
19                            It's Only the Himalayas

가격도 같이 가져오기

In [29]:
books = soup.select("article.product_pod")

data = []

for book in books:
    title = book.select_one("h3 a")["title"]
    price = book.select_one("p.price_color").get_text(strip=True)
    data.append([title, price])

df_books = pd.DataFrame(data, columns=["Title", "Price"])
df_books

                                                Title    Price
0                                A Light in the Attic  Â£51.77
1                                  Tipping the Velvet  Â£53.74
2                                          Soumission  Â£50.10
3                                       Sharp Objects  Â£47.82
4               Sapiens: A Brief History of Humankind  Â£54.23
5                                     The Requiem Red  Â£22.65
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60
9                                     The Black Maria  Â£52.15
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99
11                              Shakespeare's Sonnets  Â£20.66
12                                        Set Me Free  Â£17.46
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29
14                          Rip it Up and Start Again  Â£35.02
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25
16                                               Olio  Â£23.88
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59
18                       Libertarianism for Beginners  Â£51.33
19                            It's Only the Himalayas  Â£45.17

가격 숫자로 바꾸기

In [32]:
df_books['Price'] = df_books['Price'].str.extract(r'(\d+\.\d+)')
df_books['Price'] = df_books['Price'].astype(float)

제일 비싼 책 5개 보기

In [33]:
top5 = df_books.sort_values(by="Price", ascending=False).head(5)
top5

                                                Title  Price
15  Our Band Could Be Your Life: Scenes from the A...  57.25
4               Sapiens: A Brief History of Humankind  54.23
1                                  Tipping the Velvet  53.74
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29
9                                     The Black Maria  52.15

가격 통계 보기

In [34]:
df_books["Price"].describe()

count    20.000000
mean     38.048500
std      15.135231
min      13.990000
25%      22.637500
50%      41.380000
75%      51.865000
max      57.250000
Name: Price, dtype: float64

카테고리 이름 가져오기

In [35]:
categories = [a.get_text(strip=True) for a in soup.select("ul.nav-list ul li a")]

for c in categories:
    print(c)

Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime

카테고리 10개만 가져오기

In [36]:
categories = [a.get_text(strip=True) for a in soup.select("ul.nav-list ul li a")[:10]]

df_categories = pd.DataFrame(categories, columns=["Category"])
df_categories

             Category
0              Travel
1             Mystery
2  Historical Fiction
3      Sequential Art
4            Classics
5          Philosophy
6             Romance
7      Womens Fiction
8             Fiction
9           Childrens

책 제목 + 가격 txt 파일로 저장

In [37]:
with open("books.txt", "w", encoding="utf-8") as f:
    for i in range(len(df_books)):
        f.write(df_books.loc[i, "Title"] + " | " + str(df_books.loc[i, "Price"]) + "\n")

여러 페이지 연습

In [38]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

all_data = []

for page in range(1, 6):
    url = f"https://books.toscrape.com/catalogue/page-{page}.html"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.select("article.product_pod")

    for book in books:
        title = book.select_one("h3 a")["title"]
        price = book.select_one("p.price_color").get_text(strip=True)
        all_data.append([title, price])

    print(f"{page} page 완료")
    time.sleep(0.5)

df_all = pd.DataFrame(all_data, columns=["Title", "Price"])
df_all

1 page 완료
2 page 완료
3 page 완료
4 page 완료
5 page 완료

                                                Title    Price
0                                A Light in the Attic  Â£51.77
1                                  Tipping the Velvet  Â£53.74
2                                          Soumission  Â£50.10
3                                       Sharp Objects  Â£47.82
4               Sapiens: A Brief History of Humankind  Â£54.23
..                                                ...      ...
95  Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...  Â£19.92
96  Layered: Baking, Building, and Styling Spectac...  Â£40.11
97  Judo: Seven Steps to Black Belt (an Introducto...  Â£53.90
98                                               Join  Â£35.67
99          In the Country We Love: My Family Divided  Â£22.00

[100 rows x 2 columns]

여러 페이지 가격 숫자로 바꾸기

In [41]:
df_all['Price'] = df_all['Price'].str.extract(r'(\d+\.\d+)')
df_all['Price'] = df_all['Price'].astype(float)

df_all

                                                Title  Price
0                                A Light in the Attic  51.77
1                                  Tipping the Velvet  53.74
2                                          Soumission  50.10
3                                       Sharp Objects  47.82
4               Sapiens: A Brief History of Humankind  54.23
..                                                ...    ...
95  Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...  19.92
96  Layered: Baking, Building, and Styling Spectac...  40.11
97  Judo: Seven Steps to Black Belt (an Introducto...  53.90
98                                               Join  35.67
99          In the Country We Love: My Family Divided  22.00

[100 rows x 2 columns]

전체에서 가장 비싼 책 10개

In [42]:
df_all.sort_values(by="Price", ascending=False).head(10)

                                                Title  Price
68       The Death of Humanity: and the Case for Life  58.11
40                     Slow States of Collapse: Poems  57.31
15  Our Band Could Be Your Life: Scenes from the A...  57.25
58                                The Past Never Ends  56.50
57  The Pioneer Woman Cooks: Dinnertime: Comfort C...  56.41
91                                  Masks and Shadows  56.40
56                    The Secret of Dreadwillow Carse  56.13
67  The Electric Pencil: Drawings from Inside Stat...  56.06
25                      Birdsong: A Story in Pictures  54.64
4               Sapiens: A Brief History of Humankind  54.23