<a href="https://colab.research.google.com/github/madinayergeshbay-sudo/2026_Spring_Application_Programming/blob/main/%EA%B3%BC%EC%A0%9C34.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

import gradio as gr

In [2]:
wine = load_wine()

X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.Series(wine.target)

X.head()
y.value_counts()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

1    71
0    59
2    48
Name: count, dtype: int64

In [3]:
data = X[['alcohol', 'flavanoids', 'color_intensity']]
data.head()

   alcohol  flavanoids  color_intensity
0    14.23        3.06             5.64
1    13.20        2.76             4.38
2    13.16        3.24             5.68
3    14.37        3.49             7.80
4    13.24        2.69             4.32

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    data, y, test_size=0.2, random_state=0
)

In [5]:
model = RandomForestClassifier(random_state=0)

model.fit(X_train, y_train)

pred = model.predict(X_test)

accuracy_score(y_test, pred)

RandomForestClassifier(random_state=0)

0.9444444444444444

In [6]:
model = RandomForestClassifier(random_state=0)

model.fit(X_train, y_train)

pred = model.predict(X_test)

accuracy_score(y_test, pred)

RandomForestClassifier(random_state=0)

0.9444444444444444

In [7]:
model = RandomForestClassifier(random_state=0)

model.fit(X_train, y_train)

pred = model.predict(X_test)

accuracy_score(y_test, pred)

RandomForestClassifier(random_state=0)

0.9444444444444444

In [8]:
def wine_predict(alcohol, flavanoids, color_intensity):
    input_data = pd.DataFrame([[alcohol, flavanoids, color_intensity]],
                              columns=['alcohol', 'flavanoids', 'color_intensity'])

    result = model.predict(input_data)[0]
    wine_name = wine.target_names[result]

    return wine_name

In [9]:
app = gr.Interface(
    fn=wine_predict,
    inputs=[
        gr.Number(label="alcohol"),
        gr.Number(label="flavanoids"),
        gr.Number(label="color_intensity")
    ],
    outputs=gr.Textbox(label="Wine Class Prediction"),
    title="Wine 예측 서비스",
    description="load_wine 데이터에서 3개의 특성변수를 사용하여 와인 클래스를 예측합니다."
)

app.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://61f198210e298e3fb4.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)